Repository puppetlabs/puppetlabs-satellite_pe_tools, pull requests merged in 2021-02, with the labels that each got.

#148 (IAC-1008) - Removal of Inappropriate Terminology
  LICENSE
  README.md
  REFERENCE.md
  config/roles.yaml
  config/scripts/facts_terminus_config-3.sh
  config/scripts/facts_terminus_config.sh
  config/vms.yaml
  ext/kickstart/puppet.conf.erb
  manifests/init.pp
  spec/acceptance/test_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: bugfix

#149 pdksync - Remove Puppet 5 from testing and bump minimal version to 6.0.0
  .github/workflows/auto_release.yml
  .rubocop.yml
  .sync.yml
  .travis.yml
  metadata.json
Labels: backwards-incompatible

#151 (maint) Update major dependencies prior to release
  metadata.json
Labels: maintenance

#153 pdksync - (MAINT) PDK update for GHA workflows + Litmus updates
  .github/workflows/auto_release.yml
  metadata.json
Labels: maintenance
