Repository puppetlabs/puppetlabs-satellite_pe_tools, pull requests merged in 2022-07, with the labels that each got.

#180 report processor: load utils via absolute path
  lib/puppet/indirector/facts/satellite.rb
  lib/puppet/reports/satellite.rb
Labels: community, bug

#186 (GH-185) Fix to_yaml_spec failures
  spec/functions/to_yaml_spec.rb
Labels: maintenance

#187 (MAINT) Bump stdlib version
  metadata.json
Labels: bugfix
