Repository puppetlabs/puppetlabs-satellite_pe_tools, pull requests merged in 2023-06, with the labels that each got.

#209 (CONT-797) - Support RedHat Satellite 6.13
  .fixtures.yml
  .github/workflows/ci.yml
  Gemfile
  config/scripts/facts_terminus_config.sh
  config/scripts/install_satellite.sh
  config/scripts/redhat_repo.sh
  config/scripts/update_firewall_rules.sh
  lib/puppet/parser/functions/to_yaml.rb
  manifests/init.pp
  plans/test_01_provision.pp
  plans/test_02_server_setup.pp
  spec/acceptance/test_spec.rb
  spec/classes/init_spec.rb
  spec/functions/to_yaml_spec.rb
  spec/helper.rb
  spec/integration_helper.rb
  spec/spec_helper.rb
  spec/spec_helper_acceptance.rb
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#214 (CONT-1122) - Adding nightly GitHub action
  .github/workflows/nightly.yml
  .github/workflows/weekly.yml
Labels: maintenance

#208 pdksync - (MAINT) - Allow Stdlib 9.x
  metadata.json
Labels: feature

#213 (CONT-1123) - Add Puppet 8/Drop Puppet 6
  .fixtures.yml
  .github/workflows/release.yml
  .gitignore
  .pdkignore
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Rakefile
  Vagrantfile
  lib/puppet/indirector/facts/satellite.rb
  lib/puppet/parser/functions/parse_url.rb
  lib/puppet/reports/satellite.rb
  lib/puppet/util/satellite.rb
  metadata.json
  spec/classes/init_spec.rb
  spec/functions/parse_url_spec.rb
  spec/helper.rb
  spec/spec_helper.rb
  spec/spec_helper_acceptance_local.rb
Labels: backwards-incompatible

#218 (CONT-1131) - Updating README.md content
  README.md
Labels: maintenance

#217 (CONT-1127) - Fixing discovery of node for fetching facts
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  spec/acceptance/test_spec.rb
  spec/helper.rb
Labels: maintenance
